#!/usr/bin/python

import time, sys
from random import randint

shows = sys.argv[1:]

if not sys.stdin.isatty():
    for line in sys.stdin:
        shows = shows + [line]

if len(shows)  == 0:
    print "At least one show required"
    print "USAGE: " + sys.argv[0] + " [SHOW] ..."
    sys.exit()

print "Calculating which show to watch..."
for i in range(101):
    time.sleep(0.025)
    if i == 100 or randint(0,4) == 0:
        sys.stdout.write("\r\tProgress: %d%%" %i)
        sys.stdout.flush()
print "\nYou should watch:"
print "\t" + shows[randint(0, len(shows) - 1)]
