#!/bin/bash

cond=$(curl -s 'http://weather.yahooapis.com/forecastrss?w=2434245&u=f' | grep "yweather:condition")

text=${cond##*text=\"}
text=${text%%\"*}

temp=${cond##*temp=\"}
temp=${temp%%\"*}

battery=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | cut -d : -f 2 | tr -d ' '`

if [ -z "$temp" ]; then
    echo "$battery"
else
    echo "$temp°  $text  ($battery)"
fi
